### ISSUE TITLE
Demo3 fails with md5sum verification error

### ISSUE THREAD

**Issue by matthewpersico** [parke/lxroot#8]
Looks like the iso has changed?
```
$ make demo3
make  demo3-base    #  This allows overrding of the demo3 recipe.
make[1]: Entering directory '/home/matthew/gits/github/matthewpersico/lxroot'
if  [ ! -f /tmp/lxroot-demo/dist/archlinux-2021.06.01-x86_64.iso ]  ;  then  \
  wget  --continue  -O  /tmp/lxroot-demo/dist/archlinux-2021.06.01-x86_64.iso  https://mirror.rackspace.com/archlinux/iso/2021.06.01/archlinux-2021.06.01-x86_64.iso  ;  fi

demo3  create userland1
bash  aux/demo.sh  demo1_extract  /tmp/lxroot-demo  /tmp/lxroot-demo/demo3
demo1_extract  already done
cp  /etc/resolv.conf  /tmp/lxroot-demo/demo3/etc/
mkdir  -p  /tmp/lxroot-demo/demo3/dist
ln  -f  /tmp/lxroot-demo/dist/archlinux-2021.06.01-x86_64.iso  /tmp/lxroot-demo/demo3/dist

cp  aux/demo.sh  /tmp/lxroot-demo/demo3/root/
bin/lxroot  -nw  /tmp/lxroot-demo/demo3  \
  --  /bin/ash  /root/demo.sh  demo3_u1_create_u2
demo3_u1_create_u2
+  apk add p7zip squashfs-tools
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
OK: 13 MiB in 22 packages
md5sum  /dist/archlinux-2021.06.01-x86_64.iso
verify    md5sum  /dist/archlinux-2021.06.01-x86_64.iso
  expect  1bf76d864651cc6454ab273fd3d2226a
  actual  d41d8cd98f00b204e9800998ecf8427e
verify  failed  exiting...
make[1]: *** [Makefile:100: demo3-base] Error 1
make[1]: Leaving directory '/home/matthew/gits/github/matthewpersico/lxroot'
make: *** [Makefile:119: demo3] Error 2
```

Here's the system I am running on:
```
$ uname -a
Linux MONOLITH 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Although I have to say, this is a lxroot running in an lxroot running in a WSL2 session running on Windows. It's %#$%@!@# amazing that it all works. Kudos to you!

**Comment by parke** [comment]
Thanks for the tip about the invalid checksum.  Nice to know Lxroot works inside WSL2.  But I'm not that surprised.  All the virtualization is done by the Linux kernel, so it should "just work" (assuming the kernel is new enough).

If you are feeling adventurous, you could just update the checksum in the script and see what happens.

I'll try to get the demo fixed before Monday.  I did test demo3 a couple weeks ago.  (But maybe I used a cached copy of the ISO, hmm.)

Please let me know if you have any other questions about Lxroot.  Cheers!

**Comment by parke** [comment]
So the actual error is a 404 not found error, which makes a lot more sense.  Arch has probably deleted that old .iso file.

You should have gotten a 404 not found error the first time you ran `make demo3`.  Then, you probably ran it again.  The .iso file from the first (failed) wget is a zero byte file, but it exists, so the script checksums it, and the checksum fails.

I'll need to update the demo with a new .iso URL and checksum.  Thanks again for the bug report.

**Comment by matthewpersico** [comment]
You are welcome. All of us devs have to stick together.

**Comment by parke** [comment]
I believe `demo3` is now working in the (new) `main` branch.  Please feel free to switch to the `main` branch and try `make demo3` again.

**Comment by parke** [comment]
Update:  The `main` branch has been renamed `main-retired-20211116`.

This issue is fixed in the `main-retired-20211116` branch.  However, this issue is **not yet** fixed in `master`.

Due to other commitments, I may not have time to merge the fix into `master` until sometime in December.

Thanks again for the bug report.

**Comment by matthewpersico** [comment]
Oh good. I'm not losing my mind. Couldn't find a main branch last night and was going to comment here on it today. Thanks.

**Comment by parke** [comment]
I just published a release of version 0.21.0 of Lxroot.  I believe this issue (#8) is fixed in release 0.21.0 (and in `master`).

You may or may not wish to test demo3 at this point because...

Within the next two weeks I hope to release a new tool called `vland` in a separate repository. `vland` is a "virtual userland manager".  `vland` is a convenience wrapper around Lxroot.  `vland` is written in Dash shell.

`vland` will obsolete and replace the current demos.  Once `vland` is released, I expect to remove all the demos from the Lxroot repository.

**Comment by matthewpersico** [comment]
Thank you.

**Comment by parke** [comment]
Fyi, the first version of `vland` is now available here:
https://github.com/parke/vland

**Comment by parke** [comment]
Just fyi: I have updated `vland`.  Tutorials 1-5 are roughly equivalent to Lxroot's Demo 3.

https://github.com/parke/vland/wiki/tutorial

If you try the tutorials and encounter any issues, please open a new issue in `vland`'s issue tracker.  Thank you.
